// Error Handloing

// try-catch

// try{
//     ...normal code
// }
// catch(err){
// ...handling Error
// }


let a=3;
let b=5;

console.log("a+b=",a+b);
console.log("a-b=",a+b);
console.log("a*b=",a+b);
try{
  console.log("a+c=",a+c);  
}
catch(err){
    console.log("c is not define");
    console.log(err);

}


console.log("a/b=",a+b);
console.log("a+b=",a+b);

